language: ruby

rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - rbx-19mode
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode

gemfile:
  - gemfiles/Gemfile.ci

sudo: false
